### ISSUE TITLE
How to use the QRNN3D and MemNet methods by HyDe package?

### ISSUE THREAD

**Issue by FF-Wong** [Helmholtz-AI-Energy/HyDe#22]
How to use the QRNN3D and MemNet methods by HyDe package? 
When using "hyres = hyde.MemNet()", It will prompt that module 'hyde' has no attribute 'MemNet', but use hyde.HyMiNoR() or hyde.FastHyDe() is feasible, so I wonder how to use the QRNN3D and MemNet methods by HyDe package?

**Comment by coquelin77** [comment]
My apologies, the notification didnt come through on my email. to use the NN methods and the pretrained models, you can use the NNInference class

```python
method = hyde.NNInference(arch="qrnn3d", pretrained_file="/path/to/downloaded/model.pth")
```

**Comment by coquelin77** [comment]
I have updated the readme to clarify this.

thank you for making the issue! did this solve your problem?

**Comment by FF-Wong** [comment]
Thanks, this problem is solved, it helps a lot!
