### ISSUE TITLE
OTVCA issue

### ISSUE THREAD

**Issue by chakra65** [Helmholtz-AI-Energy/HyDe#26]
Hello,
I am trying to implement the OTVCA function.
The documentation says that it would return a 3D matrix but it returns a 2D tuuple.

It would be great if you could help me implement it.

**Comment by coquelin77** [comment]
Hello, what you are seeing is expected actually, OTVCA returns both the denoised HSI and the extracted features.

you can see this in the documentation here: https://github.com/Helmholtz-AI-Energy/HyDe/blob/main/src/hyde/transform_domain/otvca.py#L35

if there are any other issues please don't hesitate to ask

**Comment by chakra65** [comment]
Hello,

Yess I see that now.

I was expecting the output like the matlab code.
But this worked.
Thank you so much :)

Best Regards,
Rupsa
------------------------------------------------------
Dr. Rupsa Chakraborty
***@***.***

CASUS - Center for Advanced Systems Understanding,Untermarkt 20, 02826 Görlitz
https://www.casus.science &
HIF- Helmholtz Institute Freiberg for Resource Technology, 09599, Freiberg

Helmholtz-Zentrum Dresden-Rossendorf e.V. (HZDR)
